using Lesson19052022;
using System.Diagnostics;
Vector vector = new Vector(20000);
vector.InitRand(0, 100);
Console.WriteLine(vector.ToString());
Stopwatch stopwatch = new Stopwatch();
stopwatch.Start();
vector.QuickSort1(0, 19999);
stopwatch.Stop();
Console.WriteLine(vector.ToString());
Console.WriteLine(stopwatch.ElapsedMilliseconds);
//vector.InitKeyboard();
////vector.InitRand(0,10);
//Console.WriteLine(vector.ToString());
////vector.Reverse();
//int[] sub =vector.MaxSubVecror();
//Console.WriteLine(vector.ToString());
//Console.WriteLine(vector.IsPalindrom(3443));
//Console.WriteLine(vector.IsPalindrom());
//int[] arr = new int[] { 3, 4, 5, 6, 7 };
//Array.Reverse(arr);
